use num_traits::{Num, One, Zero};
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::error::Error;

/// Matrix multiplication strategy selection.
#[derive(Clone, Copy, Debug)]
pub enum Strategy {
    /// Simple nested loops.
    Naive,
    /// Parallelized simple nested loops.
    NaiveParallel,
    /// Cache-optimized single-threaded tiling.
    Tiled,
    /// Cache-optimized with parallelization.
    TiledParallel,
}

/// Configuration for matrix operations.
#[derive(Clone, Debug)]
pub struct MatrixConfig {
    /// The multiplication strategy to use.
    pub strategy: Strategy,
    /// Block size for tiled strategies. Used only on Tiled Strategies.
    pub block_size: usize,
}

impl Default for MatrixConfig {
    fn default() -> Self {
        MatrixConfig {
            strategy: Strategy::Tiled,
            block_size: 32
        }
    }
}

impl MatrixConfig {
    /// Creates a new matrix configuration with the given strategy and block size.
    pub fn new(strategy: Strategy, block_size: usize) -> Self {
        MatrixConfig { strategy, block_size }
    }
}

/// Errors that can occur during matrix operations.
#[derive(Debug, Clone)]
pub enum MatrixError {
    /// The provided data vector has an incorrect length.
    InvalidDataLength { expected: usize, got: usize },
    /// Two matrices have incompatible dimensions for an element-wise operation.
    DimensionMismatch { expected: (usize, usize), got: (usize, usize) },
    /// Two matrices have incompatible shapes for multiplication.
    IncompatibleShapes { a: (usize, usize), b: (usize, usize) },
}

impl fmt::Display for MatrixError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MatrixError::InvalidDataLength { expected, got } => {
                write!(f, "Invalid data length: expected {}, got {}", expected, got)
            }
            MatrixError::DimensionMismatch { expected, got } => {
                write!(f, "Dimension mismatch: expected {:?}, got {:?}", expected, got)
            }
            MatrixError::IncompatibleShapes { a, b } => {
                write!(f, "Incompatible matrix shapes: {}x{} and {}x{}", a.0, a.1, b.0, b.1)
            }
        }
    }
}

impl Error for MatrixError {}

/// A generic matrix supporting multiple multiplication strategies.
#[derive(Clone, Serialize)]
pub struct Matrix<T> {
    rows: usize,
    cols: usize,
    data: Vec<T>,
    #[serde(skip)]
    config: MatrixConfig,
}

impl<T> Matrix<T> {
    /// Returns the number of rows in the matrix.
    pub fn rows(&self) -> usize {
        self.rows
    }

    /// Returns the number of columns in the matrix.
    pub fn cols(&self) -> usize {
        self.cols
    }

    /// Returns a slice of the matrix data in row-major order.
    pub fn data(&self) -> &[T] {
        &self.data
    }
}

impl<T: Num + Copy> Matrix<T> {
    /// Creates a matrix from raw data with default configuration.
    ///
    /// Uses Tiled strategy with block size 32.
    ///
    /// # Errors
    /// Returns `MatrixError::InvalidDataLength` if the data length does not equal `rows * cols`.
    pub fn new(rows: usize, cols: usize, data: Vec<T>) -> Result<Matrix<T>, MatrixError> {
        Self::new_with_config(rows, cols, data, MatrixConfig::default())
    }

    /// Creates a matrix from raw data with a specified configuration.
    ///
    /// # Errors
    /// Returns `MatrixError::InvalidDataLength` if the data length does not equal `rows * cols`.
    pub fn new_with_config(
        rows: usize,
        cols: usize,
        data: Vec<T>,
        config: MatrixConfig,
    ) -> Result<Matrix<T>, MatrixError> {
        if data.len() != rows * cols {
            return Err(MatrixError::InvalidDataLength {
                expected: rows * cols,
                got: data.len(),
            });
        }
        Ok(Matrix {
            rows,
            cols,
            data,
            config,
        })
    }

    /// Creates a matrix filled with zeros using default configuration.
    pub fn zeros(rows: usize, cols: usize) -> Matrix<T>
    where
        T: Zero,
    {
        Self::zeros_with_config(rows, cols, MatrixConfig::default())
    }

    /// Creates a matrix filled with zeros with a specified configuration.
    pub fn zeros_with_config(rows: usize, cols: usize, config: MatrixConfig) -> Matrix<T>
    where
        T: Zero,
    {
        Matrix {
            rows,
            cols,
            data: vec![T::zero(); rows * cols],
            config,
        }
    }

    /// Creates a matrix with values generated by a closure using default configuration.
    pub fn random<F: FnMut() -> T>(rows: usize, cols: usize, generator: F) -> Matrix<T> {
        Self::random_with_config(rows, cols, generator, MatrixConfig::default())
    }

    /// Creates a matrix with values generated by a closure with a specified configuration.
    pub fn random_with_config<F: FnMut() -> T>(
        rows: usize,
        cols: usize,
        mut generator: F,
        config: MatrixConfig,
    ) -> Matrix<T> {
        let mut buffer = Vec::<T>::with_capacity(rows * cols);
        for _ in 0..rows * cols {
            buffer.push(generator());
        }
        Matrix {
            rows,
            cols,
            data: buffer,
            config,
        }
    }

    /// Creates an identity matrix of size `size x size` using default configuration.
    pub fn identity(size: usize) -> Matrix<T>
    where
        T: Zero + One,
    {
        Self::identity_with_config(size, MatrixConfig::default())
    }

    /// Creates an identity matrix of size `size x size` with a specified configuration.
    pub fn identity_with_config(size: usize, config: MatrixConfig) -> Matrix<T>
    where
        T: Zero + One,
    {
        let mut result_data = vec![T::zero(); size * size];
        for i in 0..size {
            result_data[i * size + i] = T::one();
        }
        Matrix {
            rows: size,
            cols: size,
            data: result_data,
            config,
        }
    }

    fn add_naive(&self, other: &Matrix<T>) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        for i in 0..rows {
            for j in 0..cols {
                let idx = i * cols + j;
                result_data[idx] = self.data[idx] + other.data[idx];
            }
        }

        Matrix {
            rows: self.rows,
            cols: self.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn add_tiled(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        for ii in (0..rows).step_by(block_size) {
            for jj in (0..cols).step_by(block_size) {
                let i_max = (ii + block_size).min(rows);
                let j_max = (jj + block_size).min(cols);

                for i in ii..i_max {
                    for j in jj..j_max {
                        let idx = i * cols + j;
                        result_data[idx] = self.data[idx] + other.data[idx];
                    }
                }
            }
        }

        Matrix {
            rows: self.rows,
            cols: self.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn subtract_naive(&self, other: &Matrix<T>) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        for i in 0..rows {
            for j in 0..cols {
                let idx = i * cols + j;
                result_data[idx] = self.data[idx] - other.data[idx];
            }
        }

        Matrix {
            rows: self.rows,
            cols: self.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn subtract_tiled(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        for ii in (0..rows).step_by(block_size) {
            for jj in (0..cols).step_by(block_size) {
                let i_max = (ii + block_size).min(rows);
                let j_max = (jj + block_size).min(cols);

                for i in ii..i_max {
                    for j in jj..j_max {
                        let idx = i * cols + j;
                        result_data[idx] = self.data[idx] - other.data[idx];
                    }
                }
            }
        }

        Matrix {
            rows: self.rows,
            cols: self.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn hadamard_naive(&self, other: &Matrix<T>) -> Matrix<T> {
        let mut result_data = vec![T::zero(); self.rows * self.cols];

        for i in 0..self.rows {
            for j in 0..self.cols {
                let idx = i * self.cols + j;
                result_data[idx] = self.data[idx] * other.data[idx];
            }
        }

        Matrix {
            rows: self.rows,
            cols: self.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn hadamard_tiled(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let mut result_data = vec![T::zero(); self.rows * self.cols];

        for ii in (0..self.rows).step_by(block_size) {
            for jj in (0..self.cols).step_by(block_size) {
                let i_max = (ii + block_size).min(self.rows);
                let j_max = (jj + block_size).min(self.cols);

                for i in ii..i_max {
                    for j in jj..j_max {
                        let idx = i * self.cols + j;
                        result_data[idx] = self.data[idx] * other.data[idx];
                    }
                }
            }
        }

        Matrix {
            rows: self.rows,
            cols: self.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    /// Returns the transpose of this matrix.
    pub fn transpose(&self) -> Matrix<T> {
        let mut buffer = vec![T::zero(); self.cols * self.rows];

        for i in 0..self.rows {
            for j in 0..self.cols {
                buffer[j * self.rows + i] = self.data[i * self.cols + j];
            }
        }

        Matrix {
            rows: self.cols,
            cols: self.rows,
            data: buffer,
            config: self.config.clone(),
        }
    }

    /// Applies a function to each element and returns a new matrix.
    pub fn apply_function<F: Fn(T) -> T>(&self, func: &F) -> Matrix<T> {
        let data: Vec<T> = self.data.iter().map(|&val| func(val)).collect();
        Matrix {
            rows: self.rows,
            cols: self.cols,
            data,
            config: self.config.clone(),
        }
    }

    fn multiply_naive(&self, other: &Matrix<T>) -> Matrix<T> {
        let mut result_data = vec![T::zero(); self.rows * other.cols];
        let n = self.rows;
        let m = self.cols;
        let p = other.cols;

        for i in 0..n {
            for j in 0..p {
                let mut sum = T::zero();
                for k in 0..m {
                    sum = sum + self.data[i * m + k] * other.data[k * p + j];
                }
                result_data[i * p + j] = sum;
            }
        }

        Matrix {
            rows: self.rows,
            cols: other.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn multiply_tiled(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let mut result_data = vec![T::zero(); self.rows * other.cols];
        let n = self.rows;
        let m = self.cols;
        let p = other.cols;

        for ii in (0..n).step_by(block_size) {
            for jj in (0..p).step_by(block_size) {
                for kk in (0..m).step_by(block_size) {
                    let i_max = (ii + block_size).min(n);
                    let j_max = (jj + block_size).min(p);
                    let k_max = (kk + block_size).min(m);

                    for i in ii..i_max {
                        for j in jj..j_max {
                            let mut sum = result_data[i * p + j];
                            for k in kk..k_max {
                                sum = sum + self.data[i * m + k] * other.data[k * p + j];
                            }
                            result_data[i * p + j] = sum;
                        }
                    }
                }
            }
        }

        Matrix {
            rows: self.rows,
            cols: other.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

}

impl<T: Num + Copy + Send + Sync> Matrix<T> {
    /// Adds this matrix to another matrix using the configured strategy.
    ///
    /// # Errors
    /// Returns `MatrixError::DimensionMismatch` if the matrices have different dimensions.
    pub fn add(&self, other: &Matrix<T>) -> Result<Matrix<T>, MatrixError> {
        if (self.rows, self.cols) != (other.rows, other.cols) {
            return Err(MatrixError::DimensionMismatch {
                expected: (self.rows, self.cols),
                got: (other.rows, other.cols),
            });
        }

        let result = match self.config.strategy {
            Strategy::Naive => self.add_naive(other),
            Strategy::NaiveParallel => self.add_naive_parallel_internal(other),
            Strategy::Tiled => self.add_tiled(other, self.config.block_size),
            Strategy::TiledParallel => self.add_tiled_parallel_internal(other, self.config.block_size),
        };
        Ok(result)
    }

    /// Subtracts another matrix from this matrix using the configured strategy.
    ///
    /// # Errors
    /// Returns `MatrixError::DimensionMismatch` if the matrices have different dimensions.
    pub fn subtract(&self, other: &Matrix<T>) -> Result<Matrix<T>, MatrixError> {
        if (self.rows, self.cols) != (other.rows, other.cols) {
            return Err(MatrixError::DimensionMismatch {
                expected: (self.rows, self.cols),
                got: (other.rows, other.cols),
            });
        }

        let result = match self.config.strategy {
            Strategy::Naive => self.subtract_naive(other),
            Strategy::NaiveParallel => self.subtract_naive_parallel_internal(other),
            Strategy::Tiled => self.subtract_tiled(other, self.config.block_size),
            Strategy::TiledParallel => self.subtract_tiled_parallel_internal(other, self.config.block_size),
        };
        Ok(result)
    }

    /// Computes the element-wise product (Hadamard product) using the configured strategy.
    ///
    /// # Errors
    /// Returns `MatrixError::DimensionMismatch` if the matrices have different dimensions.
    pub fn hadamard_product(&self, other: &Matrix<T>) -> Result<Matrix<T>, MatrixError> {
        if (self.rows, self.cols) != (other.rows, other.cols) {
            return Err(MatrixError::DimensionMismatch {
                expected: (self.rows, self.cols),
                got: (other.rows, other.cols),
            });
        }

        let result = match self.config.strategy {
            Strategy::Naive => self.hadamard_naive(other),
            Strategy::NaiveParallel => self.hadamard_naive_parallel_internal(other),
            Strategy::Tiled => self.hadamard_tiled(other, self.config.block_size),
            Strategy::TiledParallel => self.hadamard_tiled_parallel_internal(other, self.config.block_size),
        };
        Ok(result)
    }

    /// Multiplies this matrix by another matrix using the configured strategy.
    ///
    /// # Errors
    /// Returns `MatrixError::IncompatibleShapes` if the number of columns in this matrix
    /// does not equal the number of rows in the other matrix.
    pub fn multiply(&self, other: &Matrix<T>) -> Result<Matrix<T>, MatrixError> {
        if self.cols != other.rows {
            return Err(MatrixError::IncompatibleShapes {
                a: (self.rows, self.cols),
                b: (other.rows, other.cols),
            });
        }

        let result = match self.config.strategy {
            Strategy::Naive => self.multiply_naive(other),
            Strategy::NaiveParallel => self.multiply_naive_parallel_impl(other),
            Strategy::Tiled => self.multiply_tiled(other, self.config.block_size),
            Strategy::TiledParallel => self.multiply_tiled_parallel_impl(other, self.config.block_size),
        };
        Ok(result)
    }

    #[allow(clippy::needless_range_loop)]
    fn multiply_naive_parallel_impl(&self, other: &Matrix<T>) -> Matrix<T> {
        let n = self.rows;
        let m = self.cols;
        let p = other.cols;

        let result_data = (0..n)
            .into_par_iter()
            .flat_map(|i| {
                let mut row = vec![T::zero(); p];
                for j in 0..p {
                    let mut sum = T::zero();
                    for k in 0..m {
                        sum = sum + self.data[i * m + k] * other.data[k * p + j];
                    }
                    row[j] = sum;
                }
                row
            })
            .collect();

        Matrix {
            rows: self.rows,
            cols: other.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn multiply_tiled_parallel_impl(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let n = self.rows;
        let m = self.cols;
        let p = other.cols;
        let mut result_data = vec![T::zero(); n * p];

        result_data
            .par_chunks_mut(p)
            .enumerate()
            .for_each(|(i, row)| {
                for kk in (0..m).step_by(block_size) {
                    for jj in (0..p).step_by(block_size) {
                        let j_max = (jj + block_size).min(p);
                        let k_max = (kk + block_size).min(m);
                        for j in jj..j_max {
                            for k in kk..k_max {
                                row[j] = row[j] + self.data[i * m + k] * other.data[k * p + j];
                            }
                        }
                    }
                }
            });

        Matrix {
            rows: self.rows,
            cols: other.cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    #[allow(clippy::needless_range_loop)]
    fn add_naive_parallel_internal(&self, other: &Matrix<T>) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;

        let result_data = (0..rows)
            .into_par_iter()
            .flat_map(|i| {
                let mut row = vec![T::zero(); cols];
                for j in 0..cols {
                    let idx = i * cols + j;
                    row[j] = self.data[idx] + other.data[idx];
                }
                row
            })
            .collect();

        Matrix {
            rows,
            cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn add_tiled_parallel_internal(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        result_data
            .par_chunks_mut(block_size * cols)
            .enumerate()
            .for_each(|(block_idx, chunk)| {
                let ii = block_idx * block_size;
                let i_count = chunk.len() / cols;
                for i_local in 0..i_count {
                    let i = ii + i_local;
                    for jj in (0..cols).step_by(block_size) {
                        let j_max = (jj + block_size).min(cols);
                        for j in jj..j_max {
                            chunk[i_local * cols + j] =
                                self.data[i * cols + j] + other.data[i * cols + j];
                        }
                    }
                }
            });

        Matrix {
            rows,
            cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    #[allow(clippy::needless_range_loop)]
    fn subtract_naive_parallel_internal(&self, other: &Matrix<T>) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;

        let result_data = (0..rows)
            .into_par_iter()
            .flat_map(|i| {
                let mut row = vec![T::zero(); cols];
                for j in 0..cols {
                    let idx = i * cols + j;
                    row[j] = self.data[idx] - other.data[idx];
                }
                row
            })
            .collect();

        Matrix {
            rows,
            cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn subtract_tiled_parallel_internal(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        result_data
            .par_chunks_mut(block_size * cols)
            .enumerate()
            .for_each(|(block_idx, chunk)| {
                let ii = block_idx * block_size;
                let i_count = chunk.len() / cols;
                for i_local in 0..i_count {
                    let i = ii + i_local;
                    for jj in (0..cols).step_by(block_size) {
                        let j_max = (jj + block_size).min(cols);
                        for j in jj..j_max {
                            chunk[i_local * cols + j] =
                                self.data[i * cols + j] - other.data[i * cols + j];
                        }
                    }
                }
            });

        Matrix {
            rows,
            cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    #[allow(clippy::needless_range_loop)]
    fn hadamard_naive_parallel_internal(&self, other: &Matrix<T>) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;

        let result_data = (0..rows)
            .into_par_iter()
            .flat_map(|i| {
                let mut row = vec![T::zero(); cols];
                for j in 0..cols {
                    let idx = i * cols + j;
                    row[j] = self.data[idx] * other.data[idx];
                }
                row
            })
            .collect();

        Matrix {
            rows,
            cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

    fn hadamard_tiled_parallel_internal(&self, other: &Matrix<T>, block_size: usize) -> Matrix<T> {
        let rows = self.rows;
        let cols = self.cols;
        let mut result_data = vec![T::zero(); rows * cols];

        result_data
            .par_chunks_mut(block_size * cols)
            .enumerate()
            .for_each(|(block_idx, chunk)| {
                let ii = block_idx * block_size;
                let i_count = chunk.len() / cols;
                for i_local in 0..i_count {
                    let i = ii + i_local;
                    for jj in (0..cols).step_by(block_size) {
                        let j_max = (jj + block_size).min(cols);
                        for j in jj..j_max {
                            chunk[i_local * cols + j] =
                                self.data[i * cols + j] * other.data[i * cols + j];
                        }
                    }
                }
            });

        Matrix {
            rows,
            cols,
            data: result_data,
            config: self.config.clone(),
        }
    }

}

impl<'de, T> Deserialize<'de> for Matrix<T>
where
    T: Deserialize<'de> + Num + Copy,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct MatrixData<T> {
            rows: usize,
            cols: usize,
            data: Vec<T>,
        }

        let md = MatrixData::deserialize(deserializer)?;
        if md.data.len() != md.rows * md.cols {
            return Err(serde::de::Error::custom(format!(
                "Invalid data length: expected {}, got {}",
                md.rows * md.cols,
                md.data.len()
            )));
        }

        Ok(Matrix {
            rows: md.rows,
            cols: md.cols,
            data: md.data,
            config: MatrixConfig::default(),
        })
    }
}

impl<T: fmt::Display> fmt::Display for Matrix<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let max_width = self
            .data
            .iter()
            .map(|v| v.to_string().len())
            .max()
            .unwrap_or(0);

        for i in 0..self.rows {
            write!(f, "|")?;
            for j in 0..self.cols {
                let cell_str = format!(
                    "{:^width$}",
                    self.data[i * self.cols + j],
                    width = max_width
                );
                write!(f, "{}", cell_str)?;
                if j < self.cols - 1 {
                    write!(f, "  ")?;
                }
            }
            writeln!(f, "|")?;
        }
        Ok(())
    }
}

impl<T: Num + Copy> From<Vec<T>> for Matrix<T> {
    fn from(vec: Vec<T>) -> Self {
        let rows = vec.len();
        let cols = 1;
        Matrix {
            rows,
            cols,
            data: vec,
            config: MatrixConfig::default(),
        }
    }
}

